### ISSUE TITLE
[bug]: adapter vis-hqwidgets installiert die alte vis mit.

### ISSUE THREAD

**Issue by LudwigErr** [ioBroker/ioBroker.vis-2#397] opened 2024-03-07 14:08 UTC
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Bei der Installation der hqwidgets wird zwangsweise die alte VIS installiert, die auf dem Host bisher nicht vorhanden war (nur vis-2 war installiert)

### To Reproduce

install adapter vis-hqwidgets

### Expected behavior

installation der hqwidgets auf vis-2 ohne zusätzliche installation der alten vis

### Screenshots & Logfiles

iobroker host.io2 install adapter vis-hqwidgets
iobroker host.io2 Required dependency "vis" not found on this host.
iobroker NPM version: 9.6.7Installing iobroker.vis@1.5.4... (System call)

### Adapter version

2.9.32

### js-controller version

5.0.16

### Node version

v18.17.0

### Operating system

raspian

**Comment by mcm1957** [comment] 2024-03-07 14:46
This is a problem that must be fixed within the mentioned adapetr and is NOT releated to vis-2.
The problem is registerd with issue https://github.com/ioBroker/ioBroker.vis-hqwidgets/issues/56 already.

So this issue can / should be closed as vis-2 cannot control requirements of other adapters (here: vis-hqwidgets).

**Closed** 2024-03-12 16:15 UTC
Labels: bug :lady_beetle:
