### ISSUE TITLE
No connection to IOBroker objects after update

### ISSUE THREAD

**Issue by fuk1tsunakishi** [ioBroker/ioBroker.vis-2#25] opened 2022-12-14 19:24 UTC
I updated the beta version to 2.0.10 (update procedure according to https://forum.iobroker.net/topic/60398/test-adapter-vis-2-0-alpha/2). After the update I unfortunately had no connection to the IOBroker objects anymore, everything was null. In Vis 1 all worked just fine, all objects have values.

I tried deleting the vis 2 adapter in IOBroker and re-adding it, but got the same behaviour.

Is there anything I could do to undo this? I did notice that even after I deleted the adapter in IOBroker all changes I did in vis 2 still persisted. Is there some data located on the drive I could delete directly? Do you maybe want some dump or anything to prevent this for other people who update?

P.S.: You could answer in German as well if you preferred :).

Many thanks in advance,
Armin

**To Reproduce**  
Update from probably v2.0.7 to v2.0.10

**Expected behavior**  
continued connection to IOBroker objects

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

Vis 2 Objekte:
![image](https://user-images.githubusercontent.com/120597804/207693606-c3679ab9-4615-4ad3-a5bf-4cfbd54e805f.png)

Vis 1 Objekte:
![image](https://user-images.githubusercontent.com/120597804/207693893-80699d71-4574-4de5-820d-3a32373966ae.png)

**Comment by Feuer-sturm** [comment] 2023-08-19 19:08
I just checked with vis 2.2.2 and the issue is fixed on my system.
@sigi2345 @fuk1tsunakishi @Klaus101265 If not, we can reopen the issue.

**Closed by Feuer-sturm** 2023-08-19 19:08 UTC
Labels: bug, vis-v2
